apply plugin: 'com.android.application'
apply plugin: 'com.google.firebase.crashlytics'

android {
    signingConfigs {
        release {
            storeFile file('../keystore/heride_keystore.jks')
            storePassword '3embed'
            keyAlias 'heride'
            keyPassword '3embed'
        }
    }
    compileSdkVersion 34

    defaultConfig {
        applicationId "com.heride.rider"
        minSdkVersion 21
        targetSdkVersion 34
        versionCode 6
        versionName "1.0.5"
        multiDexEnabled true
        vectorDrawables.useSupportLibrary = true

        /*LIVE*/
          buildConfigField "String", "BASEURL", "\"https://api.getheride.com/\""
         resValue "string", "MQTT_HOST", "167.71.111.179"
         resValue "string", "MQTT_PORT", "2052"
         resValue "string", "MQTT_USERNAME", "heride"
         resValue "string", "MQTT_PASSWORD", "SfAZ2Xe2B8nLRC9V"

        buildConfigField "String", "TWILLIOURL", "\"https://twilio.getheride.com/\""
        buildConfigField "String", "TWILIO_DOMAIN", "\"twilio.getheride.com\""
        resValue "string", "FB_ID", "990600611610710"
        resValue "string", "MAP_KEY", "AIzaSyDMFLb-bcwaqztmHfe7LsSgLEHpgoQhD7E"//
        resValue "string", "TERMS_KEY", "_termsAndConditions.php"
        resValue "string", "PRIVACY_KEY", "_privacyPolicy.php"
        resValue "string", "PRIVACY_BASE", "https://admin.getheride.com/supportText/customer/"
        resValue "string", "FACEBOOK_SHARE", "https://www.facebook.com/getheride"
        resValue "string", "TWITTER_SHARE", "https://twitter.com/getheride"
        resValue "string", "AMAZON_ACCESS_KEY_ID", "AKIA4BYVJXVTXIU6FGM4"
        resValue "string", "AMAZON_SECRET_KEY", "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"
        resValue "string", "AMAZON_PICTURE_BUCKET", "herideapp"
        resValue "string", "LIVE_CHAT_LICENCE_NUMBER", "4711811"//
        resValue "string", "FCM_CHANNEL", "com.heride.rider"
        resValue "string", "AF_DEV_KEY", "udYrDFPK7FSCmMaSm8yPkR"
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
        }
        debug {
            minifyEnabled false
            shrinkResources false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    lint {
        abortOnError false
        checkReleaseBuilds false
    }

    packagingOptions {
        resources {
            excludes += ['META-INF/NOTICE', 'META-INF/LICENSE', 'META-INF/LICENSE.txt', 'AndroidManifest.xml']
        }
        jniLibs {
            excludes += [
                'lib/armeabi/libcardioDecider.so',
                'lib/armeabi/libclient.so',
                'lib/armeabi-v7a/libcardioRecognizer_tegra2.so',
                'lib/mips/libcardioDecider.so',
                'lib/x86/libcardioDecider.so',
                'lib/x86/libcardioRecognizer.so',
                'lib/x86/libcardioRecognizer_tegra2.so',
                'lib/x86/libopencv_core.so',
                'lib/x86/libopencv_imgproc.so',
                'lib/x86/libclient.so'
            ]
        }
    }

    namespace 'com.heride.rider'
}

final daggerVersion = '2.21'

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')

    // Firebase Crashlytics (replaces deprecated Fabric Crashlytics)
    implementation platform('com.google.firebase:firebase-bom:32.7.0')
    implementation 'com.google.firebase:firebase-crashlytics'
    implementation 'com.google.firebase:firebase-analytics'

    implementation 'com.twilio:voice-android:5.7.2'
    implementation 'com.github.livechat:chat-window-android:v2.0.3'
    implementation 'androidx.multidex:multidex:2.0.1'
    implementation 'androidx.appcompat:appcompat:1.1.0'
    implementation 'androidx.cardview:cardview:1.0.0'
    implementation 'com.google.android.material:material:1.1.0'
    implementation 'com.google.android.gms:play-services-maps:18.1.0'
    implementation 'com.google.android.gms:play-services-location:21.0.1'
    implementation 'com.google.android.gms:play-services-gcm:17.0.0'
    implementation 'com.google.android.gms:play-services-auth:20.7.0'
    implementation 'com.google.firebase:firebase-messaging'
    implementation 'com.google.android.gms:play-services-places:17.0.0'
    implementation 'com.google.code.gson:gson:2.8.9'
    implementation 'com.squareup.okhttp3:okhttp:4.10.0'
    implementation 'com.squareup.okhttp3:logging-interceptor:4.10.0'
    implementation 'io.card:android-sdk:5.5.1'
    implementation 'com.stripe:stripe-android:20.25.0'
    implementation 'com.amazonaws:aws-android-sdk-s3:2.22.0'
    implementation 'com.facebook.android:facebook-share:16.2.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'com.hbb20:ccp:2.7.0'
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    // Dependency Injection
    implementation "com.google.dagger:dagger-android:${daggerVersion}"
    implementation "com.google.dagger:dagger-android-support:${daggerVersion}"
    implementation "com.google.dagger:dagger:${daggerVersion}"
    annotationProcessor "com.google.dagger:dagger-android-processor:${daggerVersion}"
    annotationProcessor "com.google.dagger:dagger-compiler:${daggerVersion}"
    // Retrofit
    implementation 'com.squareup.retrofit2:retrofit:2.9.0'
    implementation 'com.squareup.retrofit2:converter-gson:2.9.0'
    implementation 'io.reactivex.rxjava2:rxandroid:2.1.1'
    implementation 'com.squareup.retrofit2:adapter-rxjava2:2.9.0'
    implementation project(':simplecrop')
    // Butterknife
    implementation 'com.jakewharton:butterknife:10.2.3'
    annotationProcessor 'com.jakewharton:butterknife-compiler:10.2.3'
    //MQtt server
    implementation 'org.eclipse.paho:org.eclipse.paho.android.service:1.1.1'
    implementation 'org.eclipse.paho:org.eclipse.paho.client.mqttv3:1.2.5'
    implementation project(':android-reactive-location')
    /*Phone number digits check */
    implementation 'com.googlecode.libphonenumber:libphonenumber:8.13.0'
    /*Glide*/
    implementation 'com.github.bumptech.glide:glide:4.15.1'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.15.1'

    /*Appsflyer analytics*/
    implementation 'com.appsflyer:af-android-sdk:6.12.2'
    implementation 'com.android.installreferrer:installreferrer:2.2'
}
apply plugin: 'com.google.gms.google-services'
